### ISSUE TITLE
Framerate drops continually over hours without taking more system resources

### ISSUE THREAD

**Issue by digisomni** [vircadia/vircadia#1116]
The gamerate drops lower and lower over a period of 1-24 hours of constant running. This has been reported by myself, Basinsky, and Silverfish.

My CPU, RAM, and GPU are not being taxed any more than normal however my game rate is lower.

![image](https://user-images.githubusercontent.com/69767640/112398954-ac37da00-8cdb-11eb-96f7-b81aa25a5534.png)

**Comment by JulianGro** [comment]
I see multiple problems on your screenshot:
- Physics Object Count is 355 (if I go to the same place in the hub I only get up to 100; surely a couple of people are not going to add ~370 more)
- your Entity Updates are 75/75 (I only hit up to 40 being around 20 when standing still; this might or might not be an issue and might just be because there is people there on your end)
- **your Render Rate is extremely low** (this is likely the problem your are experiencing; The Render Rate should be fairly equal to the Game Rate in a situation like this)

Your Game Rate doesn't seem particularly low to me. One thing I do notice is that my Game Rate is slightly higher even though my timings are worse.

**Comment by digisomni** [comment]
![image](https://user-images.githubusercontent.com/69767640/112573066-e7acd400-8dc1-11eb-9337-1b528e693130.png)
Here is a picture of it not being laggy on another domain. But I'm not so sure if it's domain specific, not yet at least.

**Comment by JulianGro** [comment]
You *are* looking at the floor though.

**Comment by digisomni** [comment]
It was not laggy no matter where I looked but I just wanted to get a flat BG so it was somewhat readable.

It's been suggested I run a trace this time though so I'll do that.

**Comment by SilverfishVR** [comment]
yes, sometimes render & game rate drops over time, but Interface is not using the available recourses at all, I have seen it even after just a few hours but I have also had Interface running for 10+ hours with no drop so I really have no clue as to what is causing it.

**Comment by daleglass** [comment]
#1120 could be helpful here

**Comment by digisomni** [comment]
For now, I don't think so. Will reopen or open a new one if it happens again.
