### ISSUE TITLE
Appimage on Manjaro/Arch searches for pulse/alsa libraries in wrong location

### ISSUE THREAD

**Issue by tuxfoo** [vircadia/vircadia#1269]
When I first tried using Vircadia on Manjaro the audio and microphone did not work and sometimes it would just crash from a segmentation fault on startup.

The logs indicated that
```
/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so does not exist
```

The following fixed it
```
sudo mkdir -p /usr/lib/x86_64-linux-gnu/alsa-lib/
sudo find / -iname libasound_module_pcm_pulse.so
sudo ln -s /usr/lib/alsa-lib/libasound_module_pcm_pulse.so /usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_pcm_pulse.so
```

**Comment by JulianGro** [comment]
The way I see it, we either need to remove libasound from the AppImages, or we include `libasound_module_pcm_pulse.so` in them.
At least I assume that `libasound_module_pcm_pulse.so` is called by libasound since it should already be in the AppImages if it was a direct dependency.
I guess it would be nice if we could find out what exactly calls `libasound_module_pcm_pulse.so`.

**Comment by daleglass** [comment]
I have a report that things on Manjaro are working fine, is this still a problem?

**Comment by tuxfoo** [comment]
I have not used Vircadia in a while.

I think the best way to test if this is still an issue is with a fresh Manjaro install.
I plan on setting up a separate Manjaro install for work next week, so I could do a quick test of the App image on that to see if it this is still an issue.
