### ISSUE TITLE
Sound -> Choose output device -> Test your sound doesn't loop, and doesn't allow restarting

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1453]
If allowed to play the test sound long enough, the testing noises stop, the button remains on "Stop testing", but clicking it doesn't actually do anything.

I think the test sounds should continue forever until the button is clicked, the dialog is closed. If there is a timeout it should be a pretty long one.

**Comment by Penguin-Guru** [comment]
I agree that it should continue forever until the button is clicked, but for me the test times out after 20-40 seconds or so. The button goes back to its off state. I've never actually gotten the test to play back my audio but I assume that's just my audio issues.

**Comment by daleglass** [comment]
Mm, might be Linux specific then

**Comment by Penguin-Guru** [comment]
No, I was wrong. The button to test audio input works like I described but the button to test audio output works like you described. This seems like it should be an easy fix. Maybe they didn't add an end point to the output test because they weren't sure what audio clip they wanted to use (and how long it would be).

**Comment by daleglass** [comment]
The weird thing is that it only breaks after the sound stops playing. Before that stopping actually works.

**Comment by Penguin-Guru** [comment]
bool isPlaying is not set to false in stopSound(). That's why clicking to stop the button doesn't work (after playback has ended). The reason it does work before playback ends is because the reset() function is called when the finished signal is emitted. I'm not sure why the finished signal is not received when playback ends naturally, but I assume the audio injector is deleted at that point, breaking the manual invokation of stopSound().

I'm also not sure why both of these files exist (the first one seems to be used for my client configuration):

1. interface/resources/qml/hifi/audio/PlaySampleSound.qml
2. interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml

**Comment by Penguin-Guru** [comment]
I assume the audio sample doesn't have a lot of silent recording at the end. That might be good to confirm.

**Comment by Penguin-Guru** [comment]
This issue seemed to be resolved for me. I thought I made a change that fixed it but reverting and rebuilding didn't undo the fix. Deleting my "~/.local/share/Vircadia - dev/" brought the issue back.

I deleted my "~/.local/share/Vircadia - dev/" again and rebuilt with the changes again to confirm that they resolved the issue. The issue still occurred when I tested in the start-up void, but it did not occur after connecting to The Hub and waiting for the "loading content" message to disappear (no restart in between).

I deleted "~/.local/share/Vircadia - dev" again and rebuilt to test whether the results in my previous paragraph could be reproduced without the changes. They were the same, even though I did not wait for the "loading content" message to disappear after connecting to The Hub.

Can anyone confirm that this feature works in the start-up void but not in The Hub?
