### ISSUE TITLE
Add possiblity of smoothly rotating objects in Create app

### ISSUE THREAD

**Issue by ksuprynowicz** [vircadia/vircadia#1470]
Currently create app allows rotating objects in 1 degree increments, or 22.5 degree increments while holding CTRL. A mode that allows smooth rotation when holding shift could be added for when finer adjustment is needed.

**Comment by AleziaKurdis** [comment]
I was considering to add a button to switch the increment (for HDM) 
It would have 4 mode in HMD: Free, 1deg (default), 15 deg, 22.5 deg
and 2 in Desktop: 15 deg, 22.5 deg
So the current CTRL Key would use the value of the button and Shift the Free mode
If those key are not conflictual with other feature.

Maybe we can simply replace 22,5 by 15 deg...  since both can do 45 and 90 
15 can also do 30 and 60.

**Comment by Penguin-Guru** [comment]
I haven't really used the Create app but that seems like a good idea to me. I don't know how useful this would be but I think it might be useful to make those sensitivity values for each button user configurable, perhaps with spinboxes. The spinboxes could be hidden in a customisation menu if they don't fit well with the buttons. Something to consider.

**Comment by ksuprynowicz** [comment]
> It would have 4 mode in HMD: Free, 1deg (default), 15 deg, 22.5 deg
I think that 4 modes both for HMD and Desktop would be awesome
