### ISSUE TITLE
Add option to disable logs write to disk

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#1531]
Sometimes, the log really likes to spam stuff at me, for example, currently, some avatars cause
`[12/11 20:31:20] [DEBUG] [hifi.entities] kinematic timestep =  3610.32  truncated to  1` 
messages and I really don't need to be told about it 15 times a second. Some messages are worse, logging at game loop rate.

I would like the option to pipe that into the void, or maybe disable logging altogether because even though logs are useful for bug hunting, for the most part they are never ever used.

**Comment by HifiExperiments** [comment]
we thought about this in the past because yes the logs are annoying and take up a lot of space and can even adversely affect performance BUT…as soon as we add the option to disable logs, everyone will disable them and we’ll never get useful bug reports.  I think the better solution is to just be smarter about what we log, and how often.  most things do not need to be logging every frame for sure.

certain messages, like the kinematic time stamp one, are just completely useless.  so let’s just remove it (maybe just comment it out)!  we could even just use this issue to collect the most egregious logs and disable/throttle/improve them.

**Comment by JulianGro** [comment]
There has already been PRs reducing repeated log messages: https://github.com/vircadia/vircadia/pull/387 https://github.com/vircadia/vircadia/pull/937

I feel like just as HifiExperiments said; If there is log messages occurring too often, we should rather fix the problem than just disable them.
In this case like HifiExperiments said, we should really think if there is any point in logging this anyways. Like what is it doing? Is it truncating a time sync to one decimal place? If that is the case then there is literally no point in this message and it should be deleted.
