### ISSUE TITLE
'Can't access your account?' link on login screen leads to broken page

### ISSUE THREAD

**Issue by Spiffy-Fox** [vircadia/vircadia#1585]
Link it leads to is https://metaverse.vircadia.com/users/password/new which reports a 404 error. metaverse.vircadia.com also does not seem to be right.

**Comment by digisomni** [comment]
Pegged to be solved with the Metaverse overhaul with Feathers.js. I expect we'll see that closer to Summer because it will need a bit of polishing. For now, if anyone loses their account feel free to use the contact form on the website or reach out to me directly on Discord and I can recover your account manually.
