### ISSUE TITLE
Feature Request: Ability to enable/disable scripts in Running Scripts.

### ISSUE THREAD

**Issue by 1st-BrainStormer** [vircadia/vircadia#225]
Since we are unable to browse scripts that reside on a URL, it would be nice to have a checkbox to enable/disable them in running scripts so we can load them once and then just use the checkbox.

Also it would be nice to have a custom user scripts file that if exists, gets loaded after default scripts.
and is persistent across installs.

**Comment by kasenvr** [comment]
I believe it would be appropriate to have another box then that has "not running" scripts, and they can move between the two. However as the inventory app grows, I think it will be able to all but replace the general usage of the whole Running Scripts menu for the general user as we will have the ability to put all interesting scripts, start, pause, and stop them all from the same place. We can also share said scripts live with other users.

These are upcoming features but it seems to make sense to go this route as the inventory has many more functions tightly wound into it, meaning it's less separated points and more stuff consolidated in order to help ease improvement woes and duplication of features (or forgoing features entirely e.g. leaving the running scripts menu barebones as it has been.)
