### ISSUE TITLE
Loading Screen APIs & Safe Landings Fix Suggestion

### ISSUE THREAD

**Issue by two-one-five** [vircadia/vircadia#232]
Viki Ai:
> Possibly a mustload flag for the landing stage, so that a safe arrival can be guaranteed, and also some sort of callback to tell the landing stage when enough (as defined by the world builder) of the rest is loaded that you can safely 'pull back the curtain' (ie: when to drop the view-shielding SFX).

Kalila (me):
> so yeah mustLoad to disable safe landing, readyToShow for when ready to exit load screen... but how would we know how much is enough for "readyToShow", perhaps I guess a zone property then, you define a zone that everything in that zone must load to trigger that, HOWEVER... given failure of some or one thing within to load... there's a fallback property specified like readyToShowTimeout (default: 15s) so if the zone has been waiting for more than 15seconds, or however much you set, it automatically drops the curtain anyway, as to not be stuck in limbo due to a missing almond somewhere lol

**Comment by HifiExperiments** [comment]
we had a loading screen (the interstitial page) at one point, it should still be in the code...but it was pretty much universally hated, was my impression (I certainly hated it).  the ability to walk around your world sooner is just so much better.  maybe people disagree and it should be toggleable

I think there’s just bugs in safe landing that need to be fixed

**Comment by kasenvr** [comment]
Fully agree, it wasn't the best. That's why this different way of handling it I think might help get around that as well as giving the full control to any developer(s) of a loading screen and the respective worlds.

I think that if we do it a bit like the web, we have a solid chance. "onLoad" being a big thing... knowing when the **exact** thing you want is ready can allow **you** to make the desired effect you want. So whether that's a loading screen or the safe landing kicking in, less guessing seems to be a good idea. Or at least that's my thought.

I sense trying to automate too many pivotal things when creators already are trying to make the best possible experiences really causes a lot of trouble when something *does* end up bugging out.

**Comment by kasenvr** [comment]
I thought of a really good idea, reworking or fixing safe landings or not: If you've been "loading" for more than 15 seconds, a button should show up to free yourself from safe landings if you so wish.

This API call is available at all times to kill safe landings if it's holding you up, but this button is a UI component that shows up to help you trigger that.
