### ISSUE TITLE
API Docs does not document grabbable toggling

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#234]
https://apidocs.vircadia.dev/Entities.html#.addAction is the only real area that it's shown and that's because I know what to look for. Even though grabbable is operated via the userData still.... we need some sort of documentation for that for the meantime that I hope we can tackle soon after the merge to master.

**Comment by ctrlaltdavid** [comment]
Note; See the entity "grab" property. This might be a replacement for the userData key? And perhaps the example needs updating?

**Comment by SilverfishVR** [comment]
I was under the impression that setting grabbable via userdata was legacy, from a time where grab was not a entity property?

the example could be:
```
var entityID = Entities.addEntity({
    type: "Box",
    position: Vec3.sum(MyAvatar.position, Vec3.multiplyQbyV(MyAvatar.orientation, { x: 0, y: 0.75, z: -5 })),
    dimensions: { x: 0.5, y: 0.5, z: 0.5 },
    dynamic: true,
    collisionless: false,
    grab: {
        grabbable: true,
        kinematic: false
    },
    lifetime: 300  // Delete after 5 minutes.
});

var actionID = Entities.addAction("slider", entityID, {
    axis: { x: 1, y: 0, z: 0 },
    linearLow: 0,
    linearHigh: 1.6
});
```
_Note, i changer direction to X because it does not require a desktop user to hold shift (move i Y direction) te see the action_

maybe there should be a note somewhere explaining why you see grabbable in the userdata so many places, it sure confused me to begin with.
