### ISSUE TITLE
Add Start menu entry for server console, when install

### ISSUE THREAD

**Issue by ctrlaltdavid** [vircadia/vircadia#249]

**Comment by ctrlaltdavid** [comment]
Seems to happen when do custom install. May be a Windows search / caching issue?

**Comment by kasenvr** [comment]
I think that shortcuts do not get created with silent installs. We'll want to add a way to pass a parameter to NSIS (unless that's built-in) so that's optional. For new users, ideally a silent install will not create shortcuts as the launcher *should* be the normal way to launch the interface and sandbox, but having an option would be nice.

I've recently added the ability to launch the sandbox for each install from the launcher, so that at least mitigates some of the effect of the issue.

**Comment by digisomni** [comment]
OK, so they do get created with express installs (also silent installs), I've now disabled that. We've come full circle! PR #1081
