### ISSUE TITLE
Motion smoothing

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#268]
Any motion and animation from another person can look choppy. I assume this is because it is send over the network. It would be cool to have some kind of motion smoothing for this kind of scenario.

**Comment by Aitolda** [comment]
Interestingly enough, earlier on in the HF days there was motion smoothing that I believe was removed due to complaints from the community about latency while in VR.  I'm not sure what the solution is here, but discussion is always welcome.

**Comment by Phil-Palmer** [comment]
It's worth bearing in mind that for some use cases, smoothing could be undesirable if it reduced the sharpness or precision of the movements.  Eg. a dance or drumming performance, or a tennis match.

**Comment by jug007** [comment]
That is a very good point. I guess I would still make sense though to put smoothing on animations as oppose to just any movement.
There is of course also the possibility to look at the way motion is send over the network. Sometimes people appear to be moving at ~10 fps, which is why I opened this issue. Thinking about it now; I guess most people would do that due to not having their window focused? This just gives the perception that the game is slowing down, even though it isn't.

**Comment by kasenvr** [comment]
So maybe it should be a setting to motion smooth items that are being throttled... but for anything within normal range it should be 1:1, even if it does suck for whatever reason. Is that more in line with what you meant?

I think that where we are artificially doing something, yeah, sure why not make it look better. But otherwise, it should be as accurate as possible with assistance only provided when the user/users explicitly want the system to intervene.

**Comment by daleglass** [comment]
Dev meeting: used to be implemented in the past, people didn't like it
