### ISSUE TITLE
Teleport interferes with movement.

### ISSUE THREAD

**Issue by Darlingnotin** [vircadia/vircadia#28]
On the Oculus Rift teleport interferes with your ability to turn. If you are moving forward and you push turn it stops you in your tracks and you stop moving.
The teleport button should be moved back to where it was on the right hand button B.
And when you're moving forward it should not interfere with your ability to turn. Jumping and flying should be moved back to where they were on the joystick. They should be checked and made sure that they do not interfere with each other and work the way they used to.

**Comment by SilverfishVR** [comment]
yes, actually, activating right stick Y (RY) in any direction stops your movement and the deadzone is tiny so anything but pitch perfect lateral movement stop you, even if teleport is disabled.

I messed with this when it was introduced and while I was able to add a deadzone to the teleport, it does not affect whatever function is halting movement.

My solution is to map RY to up/down movement, overriding teleport. Advantage is that it adds the ability to move down which i really missed and that it is analog. Downside is that I can't teleport because unlike all the other controls, teleport can not be mapped with the Controller api (hint, it really really should be)

**Comment by Aitolda** [comment]
My personal desire would be to revert to something similar to the old behavior, but preserve analog movement as an option. Something like:

Left Joysticks = Move Forward/backward, Strafe Left/Right
Right Joystick = Rotate Left/Right, Jump(or hold=fly)/crouch

A or X = Teleport
Y = open create
B = menu (tablet for now)

**Comment by daleglass** [comment]
Dev meeting: probably still an issue
