### ISSUE TITLE
Interface does not respect --url parameter on launch

### ISSUE THREAD

**Issue by kasenvr** [vircadia/vircadia#446]
I tried file:///, hifi://, and http://, all failed to navigate me to the right place. But passing those parameters through Windows as the interface was running worked. So something is wrong with launching interface with --url.

**Comment by kasenvr** [comment]
https://github.com/kasenvr/project-athena/commit/ad427e31a707fd347fa522cf7f52c659594b3e85 This may be related.

**Comment by ctrlaltdavid** [comment]
`--url file:///...` (with a space) works bu `--url=file:///...` (with a "=") doesn't work when starting up Interface. This was the case in v0.86.0, too. But it should be fixed.

**Comment by ctrlaltdavid** [comment]
If an instance of Interface is running, including "=" works because main.cpp uses `QCommandLineParser` to parse the command line options, and this caters both to values specified with an "=" and values specified with a " ". The results are piped through to the running Interface.exe.

If an instance of Interface is not running, including "=" does not work because Application.cpp uses `QCoreApplication::arguments()` and tests just for "--url" then returns the next argument string as the URL value.

Notes:
- QCommandLineParser handles both "--" and "-", which is another difference.
- In main.cpp, using "="  for `clockSkew` probably doesn't work because processing this doesn't use `QCommandLineParser`.
- The user docs should be updated to show the ability to use a " " between parameter and value. https://docs.vircadia.dev/developer/interface/command-line-parameters.html.

**Comment by ctrlaltdavid** [comment]
While the "--url" command line parameter has been fixed, there are many others that have similar problems to find and fix.
Plus the user docs need to be updated.

**Comment by digisomni** [comment]
This specific case should be corrected now.
