### ISSUE TITLE
Feature request: MSAA/multisample anti-aliasing

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#460]
As described [here](https://en.wikipedia.org/wiki/Multisample_anti-aliasing), MSAA is a form of anti-aliasing that differs from "normal" supersampling, in that it only supersamples pixels that are on an edge of a face, rather than every pixel.
This could really enhance the graphics quality, while still being performant enough for real world usage.

From my understanding, you could demo how the edges look would with MSAA, if you set `"viewportResolutionScale": 1` to 2. This should have a similar effect to the edges as MSAA 4x. 

As I am not sure if we have someone in the team, that knows their way around these things, and this seems like it would require quite a lot of work, I put a bounty of 300 US$ on this for now.
Potentially, if someone knows an old HiFi dev that worked on the rendering engine, it might make sense to try hire them.

**Comment by HifiExperiments** [comment]
MSAA doesn’t work for a deferred renderer, which is why we use TAA.  However, when the renderer is set to Forward, we do in fact already use MSAA, via the viewportResolutionScale that you mention

**Comment by JulianGro** [comment]
I don't see why it wouldn't work. There is apparently also demonstrations for this: https://docs.nvidia.com/gameworks/content/gameworkslibrary/graphicssamples/d3d_samples/antialiaseddeferredrendering.htm
I do see now that this might be even more complicated than I would have assumed though. And I see that the performance cost would be more significant than on forward rendering.

I don't know if it is just our TAA implementation, or if TAA is like this normally, but to me it seems worse to use TAA than no antialiasing. I see very prominent aliasing, but also "flickering" on every edge. This looks especially horrible in VR.

From what I have seen in other applications, nothing seems to compete to SSAA or MSAA in terms of image quality. Stuff like FXAA always seems to make stuff unsharp or noisy, rather than adding detail.

**Comment by HifiExperiments** [comment]
Sorry, yeah, it’s technically possible, but it’s not feasible, performance or memory-wise.

Our TAA implementation is in an unfinished state, that’s why it doesn’t look great.  There was an old PR to improve it but it was quite complex and needs to be reworked

**Comment by HifiExperiments** [comment]
(mentioned here: https://github.com/kasenvr/project-athena/issues/185)

**Comment by JulianGro** [comment]
@HifiExperiments I guess I will just need to take your word for the MSAA stuff, as I cannot implement it myself.
From how I understand it though, it should be a lot more feasable than using SSAA, which works pretty okay on my system. So while it might not be feasable for a lot of use cases, it should work fine for high end machines and, considering the development speed of graphics hardware, on future machines.

I am just pretty sceptical on how well TAA would actually work in the end, but I am definetly up for partially reimbursing anyone who took up the torch to complete the TAA implementation, as this stuff is quite important to me.

**Comment by ctrlaltdavid** [comment]
I had a look at the old HiFi PR that attempted to improve / fix TAA and documented my findings in https://github.com/kasenvr/project-athena/issues/185. tldr: to fix TAA needs a re/better implementation as new code.

I also tried using the JavaScript console to set `Render.viewportResolutionScale = 2.0;` (instead of the default value of 1.0) and it makes a worthy quality improvement in rendering.

Currently, the resolution scale value in the graphics settings dialog has a maximum of 1.0. I intend to increase this to 2.0 per https://github.com/kasenvr/project-athena/issues/548 plus fixing custom graphics settings not being remembered per https://github.com/kasenvr/project-athena/issues/35.

**Comment by HifiExperiments** [comment]
Actually, I realized I misspoke here.  "Render.getConfig("RenderMainView.PreparePrimaryBufferForward").numSamples" controls MSAA, whereas Render.viewportResolutionScale scales the resolution of the viewport.  Visually they have the same effect, but the advantage of actual MSAA is that it's hardware accelerated, which means it's **significantly** faster to do, say, 4 MSAA samples per pixel vs. scaling the viewport resolution by 2 in each dimension.  You can't sample from MSAA textures in the same way, which is why it is technically infeasible to mix MSAA with deferred rendering.

**Comment by JulianGro** [comment]
PR #576 TAA implementation seems good enough if not better than MSAA, so I have linked this issue.

**Comment by HifiExperiments** [comment]
I hate stalebot

**Comment by digisomni** [comment]
You have to be nice to him!
