### ISSUE TITLE
"click to sit" script is not clickable in VR mode

### ISSUE THREAD

**Issue by ArcadeFever** [vircadia/vircadia#529]
While in VR mode, my avatar is not able to sit on any chairs in The Hub with the "click to sit" icon on them.  Trying to click the icon with right or left controller using trigger button does noting.  Could be a bug in the script while in VR mode, or could be some kind of rendering occlusion issue while in VR mode (as possibly suggested by Silverfish).

**Comment by kasenvr** [comment]
A new client script to allow people to sit anywhere using the Sit API that is in MyAvatar should/will? be implemented to address this in a wider sense. :)

**Comment by JulianGro** [comment]
This seems to be an issue with the script.
The script in the old hub did not allow you to sit down in VR.
The script in the new hub *does* allow you to sit down in VR.

**Comment by digisomni** [comment]
This will be addressed with the Nyx UI when it is released. :)

**Comment by JulianGro** [comment]
Since this is not a problem in the Hub and the script isn't part of this codebase I am closing this issue.
The might still be domains around that use the script that doesn't work in VR.
For reference, the Hub currently uses this: https://cdn-1.vircadia.com/us-e-1/Bazaar/Worlds/HQ-HiFi/content/Releases/usefulUtilities/sit/2019-10-03_11-59-00/sitClient.js
