### ISSUE TITLE
Interface uses up all system memory in some cases

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#612]
When visiting a world with a lot of high resolution textures, the interface can lock up the system by using up all available memory.
I assume it is trying to downscale all textures at once and uses too much memory for that.
In my case we are talking about 21 8K textures on a machine with 8gb of ram and 8gb of swap (both are being completely used up). While this might be a pretty horrible use case, this domain was specifically created like that to test out the texture memory size PR #599.
The domain is currently on explore as "MotoApartment".

**Comment by daleglass** [comment]
This needs some thought and planning about how to approach this. Should the interface monitor free memory? Should be there a memory limit for textures in system RAM? What should happen if too much is used?

A possible related solution is adding a way for domains to send lower res assets to start with, so that a low spec computer (or Quest headset) never receives full res 8K textures to start with.
