### ISSUE TITLE
Wrong aspect ratio for image entities 

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#697]
When creating an image entity and adding a picture to it, the aspect ratio of the standard picture stays. This seems normal and isn't necessarily bad. If you now press the "Reset Dimensions" button, the dimensions do change, but the aspect ratio still doesn't fit the image.
Here is an image to test with:
```
https://data.moto9000.moe/domains/hub/POSTER3.png
```

**Comment by AleziaKurdis** [comment]
This is sadly not on the "Create App" side. I would say more on the engine side.

There are 2 things here:
1- **KeepAspectRatio is buggy**. It should work no matter what are the entity's dimensions.
**With a jpeg**, the ratio is attempted to be kept but it's not accurate. (Is it a precision issue causing that? Because the current result is wrong but not very far from the real thing.)
**With a png**, it's not keeping the ratio at all. The picture systematically fits the dimensions, whatever the value of KeepAspectRatio.
If we could establish what is the exact ratio, that value could be used to address the 2 issues.
**Severity: Medium**

2- **No "natural Dimension based on image"**. The default value for "natural dimensions" of the entities that are not "Model" is Vec3.ONE (1 X 1 X 1). (There is nothing specific for "Image" type to force to any "natural dimensions" bases on the image itself (which could have been base on the "ratio" (that I imagine is a known value at some point since we have a "KeepAspectRatio" properties. We could have the "natural dimensions" returning base on the ratio with the largest dimension set to 1.)
**Severity: Low**

Maybe we can rename the issue since it's not directly the "create" app.
