### ISSUE TITLE
AMD Linux, some shadows broken in Mesa 20.2.1

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#822]
I have no idea why this suddenly happens. Maybe a grahpics driver update? I am on mesa 20.2.1
![vircadia-snap-by-motofckr9k-on-2020-10-17_20-10-14](https://user-images.githubusercontent.com/11144627/96351611-e82b9b00-10bc-11eb-8fce-a66b5d06b746.jpg)

This problem does not happen on mesa 18.0.0 or 20.0.8 so this is likely a driver issue.

**Comment by daleglass** [comment]
Needs shadows enabled, goes away if they're disabled

Perhaps should be reported to Mesa?

**Comment by makitsune** [comment]
I had the same issue today updating Mesa from 20.2.1 to 20.2.2. It's maybe important to note that Mesa 20.2.2 requires LLVM 11. Downgrading back to 20.2.1 didn't work without downgrading LLVM to 10.x.x.

Zone key light breaks. Everything else seems to be fine. There were no shader compilation errors either. I'm going to try to keep looking into this and hopefully we can figure it out together

**Comment by makitsune** [comment]
I compiled Mesa from git ([mesa-git](https://aur.archlinux.org/packages/mesa-git)) just now and things seem to be working fine!

Interface reports:
```
GL Version:  4.6 (Core Profile) Mesa 21.0.0-devel (git-53660e4c4e)
GL Renderer:  Radeon RX 580 Series (POLARIS10, DRM 3.39.0, 5.9.8-arch1-1, LLVM 10.0.1)
```

However, I had to downgrade LLVM to 10.x.x in order for it to compile. Strangely, Mesa 20.2.2 doesn't work with LLVM 10.x.x (at least not on Arch), but Mesa from git does. Does this mean it's an issue with LLVM? I'm not sure what role it plays for graphics. I can only imagine for shader compilation or something...

**Comment by makitsune** [comment]
I asked around and it seems that Nvidia with LLVM 11 works fine so it's AMD only. There were some changes to AMDGPU here: https://releases.llvm.org/11.0.0/docs/ReleaseNotes.html#changes-to-the-amdgpu-target but I don't think this is related.

**Comment by JulianGro** [comment]
@makitsune have you reported the issue to mesa? I currently don't have an amd card and when I had one it was in my workstation, so I wasn't up for doing any "risky" work.
They seem to be getting a lot of vague reports, so it is probably enough to state that Mesa 20.2.1 and 20.2.2 have this issue with LLVM 11 but not with LLVM 10 and you are having problems compiling with LLVM 11. https://gitlab.freedesktop.org/mesa/mesa/-/issues

**Comment by MirceaKitsune** [comment]
I can confirm this problem. Spoke about it on Discord, was told it's AMD + Linux specific and this report mentioned. I indeed use Linux (openSUSE Tumbleweed x64) with the free video drivers (amdgpu Mesa). I can only see things if I leave the lighting settings at minimum, if I enable light and shadows everything but the sky becomes black. I hope this helps and it can be solved in the next release so AMD users can enjoy the full beauty of the environment :)

![Screenshot_20210108_043315](https://user-images.githubusercontent.com/825418/103970150-3d34f580-5170-11eb-9ab3-6786eda8dfc9.png)
![Screenshot_20210108_043329](https://user-images.githubusercontent.com/825418/103970152-3e662280-5170-11eb-9ca5-2f6aaba1fd2e.png)

**Comment by MirceaKitsune** [comment]
As this is a very problematic bug which makes it impossible for AMD Linux users to use any graphical shaders, I'd greatly appreciate any help to nail down the issue please. I started doing some in-depth investigation to help today, using the very intuitive Luci script provided by default. So far I found a few interesting things worth adding to the discussion.

First of all I was told this may be caused by shadows, however that doesn't appear to be the case: Disabling all settings for shadows won't make it go away, neither does turning off Bloom or AntiAliasing from Luci. If you go into Settings - Graphics, select Custom, then look at Rendering Effects you have 3 options: The first disables all rendering effects, the second enables local lights + fog + bloom, the third also enables shadows. The issue starts from the second setting and NOT the third one, it's only the first (which disables everything) that allows me to see anything in the world.

The only one of the options in Luci that makes it go away is setting the Render Method to Forward: The moment it's on Deferred everything goes black. So we know it's something specific to this pipeline. And sadly deferred rendering is necessary to enable any effects, the forward pipeline allows no shaders and compositing.

I played around with the Framebuffer - Debug Buffer option in Luci, very useful for checking what might break and where. @daleglass helped confirm that some suspicious results are in fact normal, such as the Lightmap pass being black and Depth / Linear Depth being white (Half Linear Depth shows a working grayscale depth buffer for me), initially I thought the Z-buffer might be broken. All other passes in this list appear fine as far as I can tell... I can even see the Shadow Cascade passes if I enable shadows, as well as the Ambient Occlusion grayscale map. I'm going to discuss only the ones I find suspicious below.

First of all Albedo: This one is weird because it renders perfectly fine, which begs the question why the world appears black! If the unlit textured pass is rendered properly by the system and isn't corrupted or missing, the problem must lie in how it's being applied and composited alongside other passes.

![Screenshot_20210109_163908](https://user-images.githubusercontent.com/825418/104095005-20e2a700-529d-11eb-921d-f2c668d50f4c.png)

The Lighting pass offers an interesting result; It displays the scene with the broken blackness just brightened ever so slightly. I'm assuming this indicates the issue is present by the time lighting is calculated, but happens before lighting occurs. I conclude this as Dale shared [his own screenshot](https://cdn.discordapp.com/attachments/659881522815303710/797475453190930442/Screenshot_20210109_154206.png) of this pass and in his it looks the same except without the problem.

![Screenshot_20210109_163931](https://user-images.githubusercontent.com/825418/104095037-55566300-529d-11eb-8df9-d57eb1bc0c49.png)

Otherwise I noticed that Ambient Occlusion on Blurred displays graphical corruption. No idea if this is related to our issue or not, but in case it's a sign of where things may be breaking it might be worth noting.

![Screenshot_20210109_164208](https://user-images.githubusercontent.com/825418/104095060-7d45c680-529d-11eb-9941-31cc0cd30fbd.png)

**Comment by makitsune** [comment]
I just did a system upgrade on Arch Linux and the issue seems to be fixed! I was surprised because I wasn't expecting it.

Here are the version numbers for related packages:
- `mesa 20.3.2-2`
- `llvm 11.0.1-1`

I found this article about LLVM 11.0.1 which states that there's been over 300 patches since the release of 11.0.0:
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-11.0.1-Tagged

Thank goodness it's fixed...

**Comment by MirceaKitsune** [comment]
openSUSE Tumbleweed currently offers Mesa 20.3.2, I still have the issue on this Mesa version. But llvm is still 11.0.0 not 11.0.1 yet: Could it have been a llvm issue then? llvm 11.0.1 is coming, likely in a week or so... once it's installed I'll give it another try and see if the problem goes away for me as well. Thanks for the heads up!

**Comment by MirceaKitsune** [comment]
Confirming the issue goes away for me as well after updating from LLVM 11.0.0 to 11.0.1. If everyone else can confirm the issue was resolved for them too this can hopefully be closed.

**Comment by JulianGro** [comment]
I am closing this issue as it has apparently been fixed in LLVM 11.0.1

**Comment by Olm-e** [comment]
can you please insure the appimage 2021.1 version is compiled with correct llvm version then so it does not have this bug ? thanks a lot ;)

**Comment by makitsune** [comment]
> can you please insure the appimage 2021.1 version is compiled with correct llvm version then so it does not have this bug ? thanks a lot ;)

Llvm is used at runtime with mesa (opengl) not compilation. Check interface's logs to see which version is being used
