### ISSUE TITLE
Discussion: Alternative Simplified 2-level LOD concept

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#849]
Idea.

user side:
Have some sort of local zone auto attached to the user when they enter a domain. Said zone expands and contracts depending on the speed  and scale of the player. (Zone expands when player moves faster)

Objects:
Some way to detect if an object (generally low poly) is within the zone mentioned above.  If it is within this player zone, it will not render, allowing another high poly object at the same position to load if set to render withing said zone,  OR the object swaps to the other object when the original is no longer rendered.

Issues:
This is sort of the opposite of the current render with zones option, which focuses on when an avatar enters a zone, and not the an object.  Not sure how two make these two concepts work together yet, but I'm tired and possibly not seeing the whole picture.

Thoughts and comments?

**Comment by HifiExperiments** [comment]
I think that this could work for simple scenes as a hack to accomplish slightly better LOD, with two caveats:

1. checking if an object is in a zone is generally expensive.  the only way renderWithZones is performant is because we were already keeping a list of which entities the avatar is inside, which we could reuse.  doing checks for many objects is not feasible

2. the growing/shrinking you describe is similar to how other parts of the system already work.  for example, the workload system has multiple rings that grow and shrink to handle scaling physics simulation based on performance.  the real solution to LOD will likely involve reusing this system to more intelligently manage multiple LOD levels.  but this doesn’t handle more complex problems, like the memory impact of loading both LOD levels, or measuring the actual GPU cost of rendering each individual model

(also, I don’t know if I’ve said this before, but the biggest reason hifi held off on implementing a better LOD system was because they knew there were more rendering performance improvements to make first, like multi draw indirect)

**Comment by Aitolda** [comment]
I appreciate you sharing your thoughts and contributing so much.  I guess I'm just super eager to be able to make expansive explorable evironments. I'm just eager to get something in motion.  I've been using render with zones extensively and it's great for making more performant experiences for those with lower end videocards.

**Comment by kasenvr** [comment]
I think automation is a great thing but also hard to get right. Making LOD tiers and letting creators define which model is in which LOD tier is a good interim perhaps?

Control would be needed even with full automation in case a world is atypical. In this case, we'd be starting from that assumption. Letting the engine scale things up and down based on the LOD settings applied (can be set using scripting so different domains can set it for you?)

One question there might be why not expose more control to the scripting API so scripts can be made to do LOD instead of in the C++? Or both!

e.g. if we switch out the marketplace pieces of packets for LOD URLs and parameters, we could just set the controls for LOD *and* create our own systems in scripting to do it if we're not happy with how the C++ handles it.

Scripting e.g. EntityID -> setLOD -> level 4.
Scripting e.g. LOD.setDistance(4, 1000); so level 4 LOD only kicks in when you're within or outside 1km, all depends on how it's setup. :)

I haven't thought through how LOD should work yet, but my examples are to show that tuning and manual control possibility should be taken into account?

**Comment by daleglass** [comment]
I think we need a big picture overview here. First, what we have, and second what we should have.

Here's my understanding of the current situation:

LOD has two parts to it: the complexity of the asset itself, and how the interface manages those assets.

On the asset part:

1. We only have asset complexity scaling on ATP.
2. But, ATP is slow.
3. Therefore, everybody uses HTTP assets, and effectively all assets have a single complexity.
4. Conclusion 1: The ATP needs fixing badly.
5. Conclusion 2: We need asset scaling on HTTP.

On the interface part:

1. The current automatic LOD mechanism is broken. The interface seems to get into a loop: slow performance results in interface dropping objects from rendering, this frees up time, interface decides it could be doing more, starts rending more again and overdoes it, drops assets from rendering again. This makes it unusable.
2. We have manual, zone based visibility system that to an extent can be used to compensate for the non-working automation.
3. Conclusion: We need to fix the interface LOD mechanism. 

Based on discussion at the dev meeting, my conclusions so far:

* We need to fix the ATP.
* We need to support asset scaling on HTTP
* We need to figure out exactly how scalable assets should work on HTTP -- can we do it without FST files, for instance by having a standard naming scheme?
* We need to take the Quest into account -- We need asset complexity scaling not just for dealing with far away stuff impacting performance but also with low powered systems that need lower complexity versions of everything to start with, both geometry and textures.
* We need to fix the interface's LOD mechanism.
* Automatic LOD needs to be possible to be adjustable by the domain's owner. There may be cases where for instance something needs to be seen from very far away.

How does this sound?

**Comment by Aitolda** [comment]
I agree these are all things that need looking into in the grand scheme.  I guess the first thing to look at is laying the groundwork for  the interface even knowing acknowledge LODs can exist, even if it's not hooked up.

**Comment by Aitolda** [comment]
As of 2021.1.0 Eos discussion is ongoing.

Revisiting and updating tag.

**Comment by Aitolda** [comment]
LODS will always be an issue until it's not. :)
