### ISSUE TITLE
2020.3.3.RC1: Shape entity gets a wrong size when the shape is updated.

### ISSUE THREAD

**Issue by AleziaKurdis** [vircadia/vircadia#956]
When updating the shape of a "Shape" entity, the entity get resized badly depending the type of shape.

![image](https://user-images.githubusercontent.com/60075796/103969675-6df73980-5134-11eb-9015-8dc221973700.png)

![image](https://user-images.githubusercontent.com/60075796/103969682-73548400-5134-11eb-8aa2-25421a1574e6.png)

![image](https://user-images.githubusercontent.com/60075796/103969688-78193800-5134-11eb-8dd9-c9c25f2271df.png)

![image](https://user-images.githubusercontent.com/60075796/103969702-823b3680-5134-11eb-9c88-283ca19bc3d5.png)

It seems to be loaded with a correct size. Anb be only inaccurate where the change is called.
But this is bad when people try to edit.

**Bug (Regression)**
Severity: **Medium**
Priority: **High**

**Comment by digisomni** [comment]
Was this issue present in 2020.3.2 or earlier?

**Comment by AleziaKurdis** [comment]
According issue #224, I can at least confirm that this was working fine in March 21th, 2020.

**Comment by HifiExperiments** [comment]
I’m looking into this

**Comment by Aitolda** [comment]
Confirmed. Interesting.

**Comment by JulianGro** [comment]
Are we sure this only happens on shapes?
I have had similar happen on models.

**Comment by HifiExperiments** [comment]
models are (intentionally, but maybe controversially) supposed to maintain their dimensions when you switch the modelURL.  so, creating a model without specifying its dimensions will spawn it at its natural dimensions, but changing its modelURL will keep it at the old model’s dimensions.

this issue is specific to shapes, and actually specific to Spheres I believe, because of an internal 0.5 scale that we have to apply to spheres due to a rendering quirk
