### ISSUE TITLE
Windows PR builds broken due to missing JOM

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#976]
Currently the Windows PR builds are failing because, OpenSSL-windows uses JOM which cannot be downloaded by 
 vcpkg/*/scripts/cmake/vcpkg_find_acquire_program.cmake because QT apparently removed it from their server.
 http://download.qt.io/official_releases/jom/jom_1_1_3.zip returns a 404
 https://download.qt.io/official_releases/jom/jom_1_1_3.zip (as used in upstream vcpkg) is unavailable

Upstream vcpkg has a mirror for JOM: https://github.com/microsoft/vcpkg/blob/4d136ef25f4fab5b744c7ae6acfa04d44f254f2b/scripts/cmake/vcpkg_find_acquire_program.cmake#L207

We could just update vcpkg to upstream as all custom vcpkg configurations are already in the codebase anyways. It should only add some deprecation warnings for the loading of components which isn't needed anymore since vcpkg just loads all components now.

**Comment by ctrlaltdavid** [comment]
Qt is currenlty having a problem with all their open source downloads due to a severe h/w failure at their cloud sourc provider.
Details:
- https://wiki.qt.io/Jom
- https://www.qt.io/blog/problem-with-open-source-downloads
- https://forum.qt.io/topic/122837/download-qt-io-is-down

Mirrors mentioned by users in the Qt forums:
- https://qt-mirror.dannhauer.de/
- https://www.funet.fi/pub/mirrors/download.qt-project.org/
- https://ftp.fau.de/qtproject/

**Comment by ctrlaltdavid** [comment]
The copy of VCPKG we use in our builds is out of date ... current VCPKG source for vcpkg_find_acquire_program(JOM) includes a a second alternative download URL that works, whereas our VCPKG just has the Qt download link.
https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_find_acquire_program/

**Comment by ctrlaltdavid** [comment]
Qt builds are working again: https://www.qt.io/blog/open-source-downloads-working-again
So Windows builds should be working OK again.
