### ISSUE TITLE
Feature Request:  Entity List - Sort by file location/URL

### ISSUE THREAD

**Issue by Aitolda** [vircadia/vircadia#977]
Right now you can sort by file name, but the origin is only shown if an entity is selected, and the properties menu is open to the correct tab.  In most cases this is fine, but at times when you wish to migrate entities to another server or location it's not easy to get a location list without going into the server settings and playing games with the domain's primary json.

Either the "File" column could be modified to show this, or a new option column could be added.  Or perhaps a toggle on the existing file column.

Thoughts?

**Comment by AleziaKurdis** [comment]
I see here a good idea for an application specialized in data migration. (definitely a need here.)
Just imagine the case where you want to archive a domain and regroup everything under a same root.
Should we have this in create app? I don't know. Add a column is relatively easy... but
One major issue I see in this, is that the findEntity used by the create application is probably not powerful enough since it excludes some entities that are to small&far to be rendered. Which is bad to do migration. (I had some surprise just trying to export as json for this reason)
So the primary json is probably the source of data that you might want to work with to do a migration.
A migration tool could offer different way to visualize the data, list of files, list of directories, list of scripts, and certainly offer some path replacement functionalities, etc.
Such a tool would be more specialized, and way less complex to maintain. 

I'm going to have this need sooner or later my-self so I might have to code it if it doesn't exist when I will need it.
I think few people have requested this, because the platform is relatively not too much crowded so far. This could change in the future.

**Comment by Aitolda** [comment]
> One major issue I see in this, is that the findEntity used by the create application is probably not powerful enough since it excludes some entities that are to small&far to be rendered. Which is bad to do migration. (I had some surprise just trying to export as json for this reason)

In all honestly, I'd probably be doing a lot more than just migration using this.  Often as I am creating I'll put things in temp locations or folders, and the next thing I know everything has gotten messy and I have entities on in various folders and even different servers/aws buckets.  Being able to quickly sort to help visualize locations would be super useful.  I agree though, a migration tool would be great too.

**Comment by AleziaKurdis** [comment]
I added this to my to do list. (Adding Full Path file column to the column that we can use)
It's probably not difficult to add.

**Comment by AleziaKurdis** [comment]
Column added in PR 1030.. I close this issue.
