### ISSUE TITLE
support the gltf 2.0 extention "KHR_materials_unlit"

### ISSUE THREAD

**Issue by SilverfishVR** [vircadia/vircadia#997]
Feature: It would be useful if materials on GLTF models that have the `KHR_materials_unlit` extension would render as unlit in Vircadia, same as setting the _unlit_ property on a material.
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_unlit/README.md

I know this is not a required part of the standard but it seems fairly well supported and exporting it unlit from blender is way more convenient than messing with material entities or fst files.

test models that have `KHR_materials_unlit`:
[unlitMonkey.glb](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/UnlitMonkey/unlitMonkey.glb)
[unlitMonkeyEmbedded.gltf](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/UnlitMonkey/unlitMonkeyEmbedded.gltf)
[unlitMonkeySeperate.gltf](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/UnlitMonkey/unlitMonkeySeperate.gltf)

And how it should look for reference:
[unlitmonkey.fst](https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/UnlitMonkey/unlitmonkey.fst)

**Comment by JulianGro** [comment]
This will very likely be part of the VRM spec, so that might be another reason for supporting this.

**Comment by JulianGro** [comment]
:angry:

**Comment by theanine3D** [comment]
I have run into this issue myself. I depend heavily on unlit materials for a lot of my projects, and because of this issue, I'm now forced to look for an alternative platform to put my projects in.

Vircadia should have strong support for unlit materials, especially since Vircadia devs plan to make a web-based version of Interface. Unlit materials are very performance friendly and would be critically important for making a web-based Interface have decent performance. Please consider fixing this issue! Thank you!

**Comment by theanine3D** [comment]
Yes, it's still an issue. It was never finished, to my knowledge. Last time I attempted it, it did not work.
